1.
SELECT * FROM EMPLOYEE AS E1 WHERE Salary > (SELECT SALARY from EMPLOYEE where ID = E1.ChiefID) 

SELECT E1.ID, E1.SALARY as S1, E2.SALARY as S2 from EMPLOYEE as E1
JOIN EMPLOYEE E2 on E1.ID = E2.ID
Where S1 > S2;

3.
SELECT DEPARTMENT_ID, COUNT(*) as CNT FROM DEPARTMENT 
GROUP BY DEPARTMENT_ID
WHERE cnt < 4

5.
SELECT DEPARTMENT_ID, SUM(SALARY) as S FROM DEPARTMENT 
GROUP BY DEPARTMENT_ID
ORDER BY S DESC

SELECT MAX(SR.S) FROM (SELECT DEPARTMENT_ID, SUM(SALARY) as S FROM DEPARTMENT GROUP BY DEPARTMENT_ID) AS SR